# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
---
name: Build Extensions
on:
  pull_request:
  push:

jobs:
  build-extension:
    name: "Build Extensions"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '8'

    - name: Setup thrift
      run: |
        wget http://archive.ubuntu.com/ubuntu/pool/universe/t/thrift/thrift-compiler_0.13.0-2build2_amd64.deb
        sudo dpkg -i thrift-compiler_0.13.0-2build2_amd64.deb
        thrift --version
        touch custom_env.sh
        echo 'export THRIFT_BIN=/usr/bin/thrift' >> custom_env.sh

    - name: Build spark connector v2
      run: |
        cd spark-doris-connector/ && /bin/bash build.sh --spark 2.3.4 --scala 2.11

    - name: Build spark connector v3
      run: |
        cd spark-doris-connector/ && /bin/bash build.sh --spark 3.1.2 --scala 2.12

